// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkZAlbg6UoK7xehc9HSAO9rBj68gVmj0',
    appId: '1:965402345376:web:a0415ee64a43942aaaeec5',
    messagingSenderId: '965402345376',
    projectId: 'minimalist-app---flutter',
    authDomain: 'minimalist-app---flutter.firebaseapp.com',
    storageBucket: 'minimalist-app---flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7gZrbs2iLCt3QDVn9_EDzuImWAZK0mk',
    appId: '1:965402345376:android:879bd35fffa5d84daaeec5',
    messagingSenderId: '965402345376',
    projectId: 'minimalist-app---flutter',
    storageBucket: 'minimalist-app---flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsAK8Z5R2D-jbK4WKeTv635hRcBbfU7yw',
    appId: '1:965402345376:ios:475e4960fc2409c3aaeec5',
    messagingSenderId: '965402345376',
    projectId: 'minimalist-app---flutter',
    storageBucket: 'minimalist-app---flutter.firebasestorage.app',
    iosClientId: '965402345376-ai0to0m6i02re74jat10fujjus5inoiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimalistChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsAK8Z5R2D-jbK4WKeTv635hRcBbfU7yw',
    appId: '1:965402345376:ios:475e4960fc2409c3aaeec5',
    messagingSenderId: '965402345376',
    projectId: 'minimalist-app---flutter',
    storageBucket: 'minimalist-app---flutter.firebasestorage.app',
    iosClientId: '965402345376-ai0to0m6i02re74jat10fujjus5inoiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.minimalistChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFkZAlbg6UoK7xehc9HSAO9rBj68gVmj0',
    appId: '1:965402345376:web:4eb21e3a8d9655f0aaeec5',
    messagingSenderId: '965402345376',
    projectId: 'minimalist-app---flutter',
    authDomain: 'minimalist-app---flutter.firebaseapp.com',
    storageBucket: 'minimalist-app---flutter.firebasestorage.app',
  );
}
